// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtjhyfmubaqfyuumsgxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0amh5Zm11YmFxZnl1dW1zZ3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzM0ODUsImV4cCI6MjA1Njg0OTQ4NX0.pRhsf3-AIfSIqkt0AkuhHwrjTDBVLheU1n3MllcSRqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);